# Generated by Django 3.0.6 on 2020-07-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200708_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='sellername',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='slug',
            field=models.CharField(default='', max_length=300),
        ),
    ]
